name: 🔒 Security Vulnerability
description: Report a security vulnerability (use private security advisory instead for sensitive issues)
title: "[Security]: "
labels: ["security", "vulnerability", "priority-high"]
projects: ["enterprise-saas-template/1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🚨 SECURITY VULNERABILITY REPORT

        **⚠️ IMPORTANT NOTICE:**

        - **For sensitive security issues:** Please use [GitHub Security Advisories](https://github.com/your-org/enterprise-saas-template/security/advisories/new) to report privately
        - **For general security concerns:** You can use this template for non-sensitive security improvements
        - **For urgent issues:** Email security@enterprise-saas-template.com directly

        This template is for security-related issues that don't require private disclosure.

  - type: checkboxes
    id: security-prerequisites
    attributes:
      label: Security Reporting Prerequisites
      description: Please confirm you understand our security reporting process
      options:
        - label: I understand that sensitive vulnerabilities should be reported via GitHub Security Advisories
          required: true
        - label: I have read the [Security Policy](../../SECURITY.md)
          required: true
        - label: This is not an immediately exploitable vulnerability requiring private disclosure
          required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: 🔍 Vulnerability Type
      description: What type of security issue is this?
      options:
        - "Authentication Bypass"
        - "Authorization Issues"
        - "Input Validation"
        - "SQL Injection"
        - "Cross-Site Scripting (XSS)"
        - "Cross-Site Request Forgery (CSRF)"
        - "Insecure Direct Object References"
        - "Security Misconfiguration"
        - "Sensitive Data Exposure"
        - "Insufficient Logging & Monitoring"
        - "Dependency Vulnerability"
        - "Cryptographic Issues"
        - "Session Management"
        - "API Security"
        - "Container Security"
        - "Infrastructure Security"
        - "Privacy Violation"
        - "Other Security Concern"
      default: 17
    validations:
      required: true

  - type: dropdown
    id: severity-assessment
    attributes:
      label: 🚨 Severity Assessment
      description: How severe do you assess this vulnerability to be?
      options:
        - "🔴 Critical - Immediate risk, system compromise possible"
        - "🟠 High - Significant risk, sensitive data exposure"
        - "🟡 Medium - Moderate risk, requires authentication"
        - "🟢 Low - Minor risk, limited impact"
        - "ℹ️ Informational - Security improvement suggestion"
      default: 4
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: 🔍 Vulnerability Description
      description: Detailed description of the security issue
      placeholder: |
        Provide a clear description of the vulnerability:
        - What is the security flaw?
        - How could it be exploited?
        - What systems/components are affected?
        - What data or functionality is at risk?
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: 🎯 Affected Components
      description: Which specific components, endpoints, or code sections are affected?
      placeholder: |
        List affected components:
        - Service names
        - API endpoints
        - File paths
        - Functions or classes
        - Dependencies
      value: |
        **Affected Services:**
        - 

        **Affected Endpoints:**
        - 

        **Affected Files:**
        - 

        **Affected Dependencies:**
        -
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Reproduction Steps
      description: Step-by-step instructions to reproduce the vulnerability
      placeholder: |
        Provide detailed steps to reproduce:
        1. Setup required (if any)
        2. Specific actions to take
        3. Expected vs actual security behavior
        4. Evidence of the vulnerability

        Note: Do not include actual exploit code if this could cause harm
      value: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: textarea
    id: impact-analysis
    attributes:
      label: 💥 Impact Analysis
      description: What is the potential impact of this vulnerability?
      placeholder: |
        Describe the potential impact:
        - What could an attacker achieve?
        - What data could be compromised?
        - What systems could be affected?
        - What is the business impact?
        - How many users could be affected?
      value: |
        **Confidentiality Impact:**
        - 

        **Integrity Impact:**
        - 

        **Availability Impact:**
        - 

        **Business Impact:**
        -
    validations:
      required: true

  - type: dropdown
    id: attack-vector
    attributes:
      label: 🌐 Attack Vector
      description: How could this vulnerability be exploited?
      multiple: true
      options:
        - "Network - Remote exploitation over network"
        - "Adjacent Network - Local network access required"
        - "Local - Local system access required"
        - "Physical - Physical access required"
        - "Social Engineering - Human interaction required"
        - "Supply Chain - Through dependencies or third parties"
        - "Insider Threat - Requires internal access"
    validations:
      required: true

  - type: dropdown
    id: authentication-required
    attributes:
      label: 🔐 Authentication Required
      description: What level of authentication is required to exploit this?
      options:
        - "None - Anonymous access sufficient"
        - "User - Regular user authentication required"
        - "Admin - Administrative privileges required"
        - "Service - Service-to-service authentication required"
        - "Physical - Physical device access required"
    validations:
      required: true

  - type: textarea
    id: environment-details
    attributes:
      label: 🌍 Environment Details
      description: Environment where the vulnerability was discovered
      value: |
        **Environment Type:**
        - [ ] Production
        - [ ] Staging
        - [ ] Development
        - [ ] Local

        **Version Information:**
        - Template Version: 
        - Node.js Version: 
        - Database Version: 
        - Browser (if applicable): 

        **Configuration:**
        - Authentication method: 
        - Database type: 
        - Deployment method:
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: 📋 Evidence
      description: Provide evidence of the vulnerability (logs, screenshots, etc.)
      placeholder: |
        Include relevant evidence:
        - Error messages or logs
        - Screenshots (remove sensitive data)
        - Network requests/responses
        - Code snippets showing the issue

        ⚠️ Please redact any sensitive information
      render: shell
    validations:
      required: false

  - type: textarea
    id: mitigation-suggestions
    attributes:
      label: 🛡️ Suggested Mitigation
      description: Do you have suggestions for how to fix this vulnerability?
      placeholder: |
        Suggest potential fixes:
        - Code changes needed
        - Configuration changes
        - Additional security controls
        - Best practices to implement
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 📚 References
      description: Relevant security references, CVEs, or documentation
      placeholder: |
        Include relevant references:
        - CVE numbers
        - Security advisories
        - OWASP documentation
        - Research papers
        - Similar vulnerabilities
    validations:
      required: false

  - type: checkboxes
    id: compliance-impact
    attributes:
      label: 📋 Compliance Impact
      description: Does this vulnerability affect compliance requirements?
      options:
        - label: This affects GDPR compliance
        - label: This affects SOC 2 compliance
        - label: This affects ISO 27001 compliance
        - label: This affects industry-specific regulations
        - label: This affects data retention policies

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional Context
      description: Any additional context about this vulnerability
      placeholder: |
        Additional information:
        - Timeline considerations
        - Related security issues
        - Workarounds currently in place
        - Third-party communications needed
    validations:
      required: false

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: 🤝 Responsible Disclosure
      description: Responsible disclosure commitment
      options:
        - label: I commit to responsible disclosure practices
          required: true
        - label: I will not publicly disclose details until a fix is available
          required: true
        - label: I am willing to work with the security team on remediation
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## 🚨 Important Reminders

        - **Do not include actual exploit code** that could be immediately harmful
        - **Redact sensitive information** from logs and screenshots
        - **Use GitHub Security Advisories** for sensitive vulnerabilities
        - **Contact security@enterprise-saas-template.com** for urgent issues

        Thank you for helping keep the Enterprise SaaS Template secure! 🔒
